MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Controllers/IstatistikController.cs
using System;
using System.Collections.Generic;
using MVC_Ticari_Otomasyon.Models.Siniflar;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Ticari_Otomasyon.Controllers
{
    public class IstatistikController : Controller
    {
        Context context = new Context();

        // GET: Istatistik
        public ActionResult Index()
        {
            var deger1 = context.Cariler.Count().ToString();
            ViewBag.d1 = deger1;

            var deger2 = context.Urunler.Count().ToString();
            ViewBag.d2 = deger2;

            var deger3 = context.Personeller.Count().ToString();
            ViewBag.d3 = deger3;

            var deger4 = context.Kategoriler.Count().ToString();
            ViewBag.d4 = deger4;

            var deger5 = context.Urunler.Sum(x => x.UrunStok).ToString();     //Stok Sayısı
            ViewBag.d5 = deger5;

            var deger6 = (from x in context.Urunler select x.UrunMarka).Distinct().Count().ToString();     //Marka Sayısı
            ViewBag.d6 = deger6;

            var deger7 = context.Urunler.Count(x => x.UrunStok <= 20).ToString();
            ViewBag.d7 = deger7;

            var deger8 = (from x in context.Urunler orderby x.UrunSatisFiyati descending select x.UrunAdi).FirstOrDefault();    //Max Fiyatlı Ürün Adı
            ViewBag.d8 = deger8;

            var deger9 = (from x in context.Urunler orderby x.UrunSatisFiyati ascending select x.UrunAdi).FirstOrDefault();    //Min Fiyatlı Ürün Adı
            ViewBag.d9 = deger9;

            var deger10 = context.Urunler.GroupBy(x => x.UrunMarka).OrderByDescending(x => x.Count()).Select(y => y.Key).FirstOrDefault();
            ViewBag.d10 = deger10;

            var deger11 = context.Urunler.Count(x => x.UrunAdi == "Buzdolabı").ToString();
            ViewBag.d11 = deger11;

            var deger12 = context.Urunler.Count(x => x.UrunAdi == "Laptop").ToString();
            ViewBag.d12 = deger12;

            //var deger13 = (from x in context.SatisHareketleri orderby x.SatisHareketAdedi descending select x.Urun.UrunAdi).Distinct().ToString();
            var deger13 = context.Urunler.Where(u => u.UrunID == (context.SatisHareketleri.GroupBy(x => x.Urunid).OrderByDescending(z => z.Count()).Select(y => y.Key).FirstOrDefault())).Select(k => k.UrunAdi).FirstOrDefault();
            ViewBag.d13 = deger13;

            var deger14 = context.SatisHareketleri.Sum(x => x.SatisHareketToplamTutari).ToString();
            ViewBag.d14 = deger14;

            DateTime bugun = DateTime.Today;
            var deger15 = context.SatisHareketleri.Count(x => x.SatisHareketTarihi == bugun).ToString();
            ViewBag.d15 = deger15;

            var deger16 = context.SatisHareketleri.Where(x => x.SatisHareketTarihi == bugun).Sum(x => (decimal?)x.SatisHareketToplamTutari).ToString();  //Bugün kasa tutarı null olursa hata vermemesi için (decimal?) ifadesini yazdık.

            if (deger16 == null || deger16 == "")
            {
                deger16 = "0,00 ₺";
                ViewBag.d16 = deger16;
            }
            else
            {
                ViewBag.d16 = deger16;
            }


            return View();
        }


        public ActionResult KolayTablolar()
        {
            var sorgu = (from x in context.Cariler
                         group x by x.CariSehir into g
                         select new SinifGrup1
                         {
                             Sayi = g.Count(),
                             Sehir = g.Key
                         });
            return View(sorgu.ToList());
        }







        public PartialViewResult Partial1()
        {
            var sorgu2 = (from x in context.Personeller
                          where x.PersonelDurumu == true
                          group x by x.Departman.DepartmanAdi into g
                          select new SinifGrup2
                          {
                              Sayi = g.Count(),
                              Departman = g.Key
                          });
            return PartialView(sorgu2.ToList());
        }





        public PartialViewResult Partial2()
        {
            var cariler = context.Cariler.ToList();
            return PartialView(cariler);
        }




        public PartialViewResult Partial3()
        {
            var sorgu = context.Urunler.ToList();
            return PartialView(sorgu);
        }



        public PartialViewResult Partial4()
        {
            var sorgu2 = (from x in context.Urunler
                          where x.UrunDurumu == true
                          group x by x.UrunMarka into g
                          select new SinifGrup3
                          {
                              Sayi = g.Count(),
                              Marka = g.Key
                          });
            return PartialView(sorgu2.ToList());
        }



        public PartialViewResult Partial5()
        {
            var sorgu2 = (from x in context.Urunler
                          where x.UrunDurumu == true
                          group x by x.Kategori.KategoriAdi into g
                          select new SinifGrup4
                          {
                              Sayi = g.Count(),
                              KategoriAdi = g.Key
                          });
            return PartialView(sorgu2.ToList());
        }
    }
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Istatistik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="js/zingchart.min.js"></script>
    <script src="js/zingchart.jquery.js"></script>
    <script src="js/jquery.easydropdown.js"></script>
    <script src="js/jquery.nicescroll.js"></script>

    <link href="css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <br />
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Toplam Cari</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Ürün Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Personel Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Kategori Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Toplam Stok</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Marka Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Kritik Seviye</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.d8</h3>
                    <p>Max Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.d9</h3>
                    <p>Min Fiyatlı Ürün</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.d12</h3>
                    <p>Max Marka</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.d10</h3>
                    <p>Buzdolabı Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.d11</h3>
                    <p>Laptop Sayısı</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.d13</h3>
                    <p>En Çok Satan</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.d14 ₺</h3>
                    <p>Kasadaki Tutar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.d15</h3>
                    <p>Bugünkü Satışlar</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.d16 ₺</h3>
                    <p>Bugünkü Kasa</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Istatistik/KolayTablolar.cshtml
@model IEnumerable<MVC_Ticari_Otomasyon.Models.Siniflar.SinifGrup1>
@{
    ViewBag.Title = "KolayTablolar";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Simple Tables</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Hızlı Bakış Tabloları</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        @Html.Action("Partial5", "Istatistik")
                        <!-- /.card -->
                        @Html.Action("Partial1", "Istatistik")

                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Müşteri Şehir Tablosu</h3>

                                @*<div class="card-tools">
                    <ul class="pagination pagination-sm float-right">
                        <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                    </ul>
                </div>*@
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Müşteri Şehirleri</th>
                                            <th>Şehrin Doluluğu</th>
                                            <th>Cari Sayısı</th>
                                            <th style="width: 40px">Oran</th>
                                        </tr>
                                    </thead>
                                    @{ int siraNo = 0;}
                                    @foreach (var item in Model)
                                    {
                                        <tbody>
                                            <tr>
                                                <td>@{siraNo += 1;} @siraNo</td>
                                                <td>@item.Sehir</td>
                                                <td>
                                                    @if (item.Sayi >= 1 && item.Sayi < 3)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-danger" style="width:13%"></div>
                                                        </div>
                                                    }
                                                    @if (item.Sayi >= 3 && item.Sayi < 7)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-warning" style="width: 37%"></div>
                                                        </div>
                                                    }
                                                    @if (item.Sayi >= 7 && item.Sayi < 10)
                                                    {
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-blue" style="width: 63%"></div>
                                                        </div>
                                                    }
                                                    @if (item.Sayi >= 10)
                                                    {
                                                        <div class="progress progress-xs progress-striped active">
                                                            <div class="progress-bar bg-success" style="width: 88%"></div>
                                                        </div>
                                                    }
                                                </td>
                                                <td>
                                                    @if (item.Sayi >= 1 && item.Sayi < 3)
                                                    {
                                                        <span class="badge bg-danger">@item.Sayi</span>
                                                    }
                                                    @if (item.Sayi >= 3 && item.Sayi < 7)
                                                    {
                                                        <span class="badge bg-warning">@item.Sayi</span>
                                                    }
                                                    @if (item.Sayi >= 7 && item.Sayi < 10)
                                                    {
                                                        <span class="badge bg-success">@item.Sayi</span>
                                                    }
                                                    @if (item.Sayi >= 10)
                                                    {
                                                        <span class="badge bg-success">@item.Sayi</span>
                                                    }
                                                </td>
                                                <td>
                                                    @if (item.Sayi >= 1 && item.Sayi < 3)
                                                    {
                                                        <span class="badge bg-danger">%0-%25</span>
                                                    }
                                                    @if (item.Sayi >= 3 && item.Sayi < 7)
                                                    {
                                                        <span class="badge bg-warning">%25-%50</span>
                                                    }
                                                    @if (item.Sayi >= 7 && item.Sayi < 10)
                                                    {
                                                        <span class="badge bg-success">%50-%75</span>
                                                    }
                                                    @if (item.Sayi >= 10)
                                                    {
                                                        <span class="badge bg-success">%75-%100</span>
                                                    }
                                                </td>
                                            </tr>
                                        </tbody>
                                    }
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                        @Html.Action("Partial4", "Istatistik")
                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                @Html.Action("Partial2", "Istatistik")
                <!-- /.row -->
                @Html.Action("Partial3", "Istatistik")
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->

        

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Istatistik/Partial1.cshtml
@model IEnumerable<MVC_Ticari_Otomasyon.Models.Siniflar.SinifGrup2>
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Departman Personel Sayıları</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Departman</th>
                    <th>Doluluk</th>
                    <th>Personel Sayısı</th>
                    <th style="width: 40px">Oran</th>
                </tr>
            </thead>
            <tbody>
                @{ int siraNo = 0;}
                @foreach (var item in Model)
                {
                <tr>
                    <td>@{siraNo += 1;} @siraNo</td>
                    <td>@item.Departman</td>
                    <td>
                        @if (item.Sayi >= 1 && item.Sayi <= 3)
                        {
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-danger" style="width:13%"></div>
                            </div>
                        }
                        @if (item.Sayi > 3 && item.Sayi <= 6)
                        {
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-warning" style="width: 37%"></div>
                            </div>
                        }
                        @if (item.Sayi > 6 && item.Sayi < 10)
                        {
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-blue" style="width: 63%"></div>
                            </div>
                        }
                        @if (item.Sayi >= 10)
                        {
                            <div class="progress progress-xs progress-striped active">
                                <div class="progress-bar bg-success" style="width: 88%"></div>
                            </div>
                        }
                    </td>
                    <td>
                        @if (item.Sayi >= 1 && item.Sayi <= 3)
                        {
                            <span class="badge bg-danger">@item.Sayi</span>
                        }
                        @if (item.Sayi > 3 && item.Sayi <= 6)
                        {
                            <span class="badge bg-warning">@item.Sayi</span>
                        }
                        @if (item.Sayi > 6 && item.Sayi < 10)
                        {
                            <span class="badge bg-success">@item.Sayi</span>
                        }
                        @if (item.Sayi >= 10)
                        {
                            <span class="badge bg-success">@item.Sayi</span>
                        }
                    </td>
                    <td>
                        @if (item.Sayi >= 1 && item.Sayi <= 3)
                        {
                            <span class="badge bg-danger">%0-%25</span>
                        }
                        @if (item.Sayi > 3 && item.Sayi <= 6)
                        {
                            <span class="badge bg-warning">%25-%50</span>
                        }
                        @if (item.Sayi > 6 && item.Sayi < 10)
                        {
                            <span class="badge bg-success">%50-%75</span>
                        }
                        @if (item.Sayi >= 10)
                        {
                            <span class="badge bg-success">%75-%100</span>
                        }
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Istatistik/Partial2.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@model List<Cari>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Cariler Hover Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Aranacak kelime...">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Cari Adı</th>
                            <th>Cari Soyadı</th>
                            <th>Cari Şehri</th>
                            <th>Cari Maili</th>
                            <th>Cari Durumu</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{int sayac = 0;}
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@{sayac += 1;} @sayac</td>
                                <td>@item.CariAdi</td>
                                <td>@item.CariSoyadi</td>
                                <td>@item.CariSehir</td>
                                <td>@item.CariMaili</td>
                                <td>
                                    @{ var durum = "";}
                                    @if (item.CariDurumu)
                                    {
                                        durum = "Aktif";
                                    }
                                    else
                                    {
                                        durum = "Pasif";
                                    }
                                    @durum
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Istatistik/Partial3.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@model List<Urun>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Ürün Fixed Bilgi Tablosu</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Aranacak kelime...">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Ürün Adı</th>
                            <th>Ürün Markası</th>
                            <th>Ürün Stoğu</th>
                            <th>Ürün Alış Fiyatı</th>
                            <th>Ürün Satış Fiyatı</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{int sayac = 0;}
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@{sayac += 1;} @sayac</td>
                                <td>@item.UrunAdi</td>
                                <td>@item.UrunMarka</td>
                                <td>@item.UrunStok</td>
                                <td>@item.UrunAlisFiyati ₺</td>
                                <td>@item.UrunSatisFiyati ₺</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>