MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Models/Siniflar/Departman.cs
using MVC_Ticari_Otomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Ticari_Otomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmanID { get; set; }


        [Display(Name = "Departman Adı")]
        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "Departman adı için en fazla 30 karakter girilebilir!")]
        public string DepartmanAdi { get; set; }



        
        private bool _ilkDurumDegeri = true;


        [Display(Name = "Departman Durumu")]
        [Column(TypeName = "bit")]
        public bool DepartmanDurumu
        {
            get
            {
                return _ilkDurumDegeri;
            }
            set
            {
                _ilkDurumDegeri = value;
            }
        }

        
        [Display(Name = "Departman Kapasitesi")]
        [Range(1, 250, ErrorMessage = "Departman kapasitesi en az 1, en fazla 250 olabilir!")]
        //[Required(ErrorMessage = "Departman kapasitesi tanımlayınız!")]
        public int DepartmanKapasitesi { get; set; }





        public ICollection<Personel> Personels { get; set; }                 ///1 SatisHareketinin 1'den fazla(Çok) Ürünü olabilir
    }
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using MVC_Ticari_Otomasyon.Models.Siniflar;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace MVC_Ticari_Otomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Alert
        Context context = new Context();

        // GET: Departman
        public ActionResult DepartmanListesi(string aranacakKelime, int sayfa = 1)
        {
            var departman = from x in context.Departmanlar where x.DepartmanDurumu == true select x;
            if (!string.IsNullOrEmpty(aranacakKelime))
            {
                departman = departman.Where(y => y.DepartmanAdi.Contains(aranacakKelime));
            }

            foreach (var item in departman.Where(x => x.DepartmanKapasitesi > 150))
            {
                string mesaj = "Kapasite 150'yi aşmıştır. Son 100 kayıt kapasitesi kalmıştır!";
                return View(mesaj); 
            }


            return View(departman.ToList().ToPagedList(sayfa, 10));


            //var degerler = context.Departmanlar.Where(x=>x.DepartmanDurumu==true).ToList().ToPagedList(sayfa, 10);      //ilgili sayfada sadece ilk 4 kategoriyi göster;
            //return View(degerler);
        }





        public ActionResult PasifDepartmanListesi(string aranacakKelime, int sayfa = 1)
        {
            var departman = from x in context.Departmanlar where x.DepartmanDurumu == false select x;
            if (!string.IsNullOrEmpty(aranacakKelime))
            {
                departman = departman.Where(y => y.DepartmanAdi.Contains(aranacakKelime));
            }


            return View(departman.ToList().ToPagedList(sayfa, 10));


            //var degerler = context.Departmanlar.Where(x => x.DepartmanDurumu == false).ToList();
            //return View(degerler);
        }






        public ActionResult DepartmaniAktifEt(int id)
        {
            var deger = context.Departmanlar.Find(id);
            deger.DepartmanDurumu = true;
            context.SaveChanges();
            return RedirectToAction("DepartmanListesi");
        }







        [HttpGet]
        [Authorize(Roles = "A")]
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(Departman departman)
        {
            context.Departmanlar.Add(departman);
            context.SaveChanges();
            return RedirectToAction(nameof(DepartmanListesi));
        }







        public ActionResult DepartmanGetir(int id)
        {
            //List<SelectListItem> deger1 = (from x in context.Departmanlar.ToList()       //Departman Listesinden dropdown ile listeleme yapması için Linq                                                                                   sorgusunu yazdım
            //                               select new SelectListItem
            //                               {
            //                                   Text = x.DepartmanAdi,                    //Formda seçilen departman adını text'e basıcak
            //                                   Value = x.DepartmanID.ToString()          //Text'e basılan departmanın ID'sini Value olarak saklayacak.
            //                               }).ToList();
            //ViewBag.dgr1 = deger1;


            var deger = context.Departmanlar.Find(id);
            return View("DepartmanGetir", deger);         //Bu ID'ye sahip olanın bilgileriyle birlikte DepartmanGuncelle Sayfasını Getir
        }


        public ActionResult DepartmanGuncelle(Departman departman)
        {
            var deger = context.Departmanlar.Find(departman.DepartmanID);
            deger.DepartmanAdi = departman.DepartmanAdi;
            deger.DepartmanKapasitesi = departman.DepartmanKapasitesi;
            deger.DepartmanDurumu = departman.DepartmanDurumu;
            context.SaveChanges();
            return RedirectToAction("DepartmanListesi");
        }






        //[HttpGet]
        //public ActionResult DepartmanSil()
        //{
        //    return View();
        //}

        //[HttpPost]
        public ActionResult DepartmanSil(int id)
        {
            var deger = context.Departmanlar.Find(id);
            deger.DepartmanDurumu = false;
            context.SaveChanges();
            return RedirectToAction("DepartmanListesi");
        }






        public ActionResult DepartmanDetayi(int id)
        {
            var degerler = context.Personeller.Where(x => x.Departmanid == id).ToList();
            var departman = context.Departmanlar.Where(x => x.DepartmanID == id).Select(y => y.DepartmanAdi).FirstOrDefault();
            ViewBag.DepartmanAdi = departman;
            return View(degerler);
        }






        public ActionResult DepartmanPersonelSatis(int id)
        {
            var degerler = context.SatisHareketleri.Where(x => x.Personelid == id).ToList();
            var personel = context.Personeller.Where(x => x.PersonelID == id).Select(y => y.PersonelAdi + " " + y.PersonelSoyadi).FirstOrDefault();
            var departman = context.Personeller.Where(x => x.PersonelID == id).Select(y => y.Departman.DepartmanAdi).FirstOrDefault();
            ViewBag.DepartmanAdi = departman;
            ViewBag.DepartmanPersoneliSatisi = personel;
            return View(degerler);
        }








        //public ActionResult DepartmaniYazdir(int id)      //Sadece bu departmanın özelliklerini yazdırmak için bu kod gerekli
        //{
        //    var degerler = context.Departmanlar.Where(x => x.DepartmanID == id).ToList();
        //    return View(degerler);
        //}


        public ActionResult DepartmanlariYazdir()
        {
            var degerler = context.Departmanlar.ToList();
            return View(degerler);
        }
    }
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmanDetayi.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetayi";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Personel Listesi</h2>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.DepartmanAdi Departmanı</li>
</ol>


<table class="table table-hover">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Personel Görseli</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Personel Adı</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Personel Soyadı</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Gerçekleştirilen İşlem</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">
                @if (item.PersonelGorseli == null || item.PersonelGorseli == "")
                {
                    <img src="~/Images/resim-yok.png" width="80" height="80" />
                }
                else
                {
                    <img src="@item.PersonelGorseli" width="80" height="80" />
                }
            </td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.PersonelAdi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.PersonelSoyadi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center"><a href="/Departman/DepartmanPersonelSatis/@item.PersonelID" class="btn btn-default" style="background-color:coral;">Satışlar</a></td>
        </tr>
    }
</table>
<a href="/Departman/DepartmanListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Departman Listesi</a>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmanEkle.cshtml
@model MVC_Ticari_Otomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Ekleme Sayfası</h2>
<br />

<form class="form-group" method="post">

    Departman Adı
    @Html.TextBoxFor(x => x.DepartmanAdi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.DepartmanAdi, "", new { @style = "color:red" })
    <br />

    Departman Kapasitesi
    @Html.TextBoxFor(z => z.DepartmanKapasitesi, new { @class = "form-control", @type = "number" })
    @Html.ValidationMessageFor(x => x.DepartmanKapasitesi, "", new { @style = "color:red" })
    <br />

    <button class="btn btn-success">Kaydet</button>
    <a href="/Departman/DepartmanListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Departman Listesi</a>
</form>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmanGetir.cshtml
@model MVC_Ticari_Otomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.DepartmanID)

        Departman Adı
        @Html.TextBoxFor(z => z.DepartmanAdi, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.DepartmanAdi, "", new { @style = "color:red" })
        <br />

        Departman Kapasitesi
        @Html.TextBoxFor(z => z.DepartmanKapasitesi, new { @class = "form-control", @type="number" })
        @Html.ValidationMessageFor(x => x.DepartmanKapasitesi, "", new { @style = "color:red" })
        <br />
    </div>
    <br />
    <button class="btn" style="background-color:#a725a4; color:antiquewhite">Değişiklikleri Kaydet</button>
    <a href="/Departman/DepartmanListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Departman Listesi</a>
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmanListesi.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList<Departman>
@*@model List<Departman>*@
@{ ViewBag.Title = "DepartmanListesi";
                Layout = "~/Views/Shared/AdminLayout.cshtml"; }

<br />

@using (Html.BeginForm("DepartmanListesi", "Departman", FormMethod.Get))
{
<p>
    Departman Adı : @Html.TextBox("aranacakKelime")
    <input type="submit" value="Ara" />
</p>}

<table class="table table-bordered" style="margin-top:20px;">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Adı</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Kapasitesi</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">İşlemler</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
<tr>
    <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
    <td style="display:table table-cell; vertical-align:middle;">@item.DepartmanAdi</td>
    <td style="display:table table-cell; vertical-align:middle;">@item.DepartmanKapasitesi</td>
    <td style="display:table table-cell; vertical-align:middle;" class="text-center">
        <a href="/Departman/DepartmanDetayi/@item.DepartmanID" class="btn" style="background-color:forestgreen; color:aliceblue">Detay</a>
        <a href="/Departman/DepartmanGetir/@item.DepartmanID" class="btn" style="background-color:darkorange; color:aliceblue">Güncelle</a>
        <a href="/Departman/DepartmanSil/@item.DepartmanID" class="btn" style="background-color:firebrick; color:aliceblue">Sil</a>
    </td>
</tr>}
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("DepartmanListesi", new { sayfa }),
new PagedListRenderOptions@*Sayfa değerine her tıklandığında, yeni bir sayfa oluşturarak bana Kategori Listesini aç*@
{
                LiElementClasses = new List<string>
            {
"page-link"         //Sayfanın linklerini ekle
                }
            })

<a href="/Departman/DepartmanEkle" class="btn btn-info">Departman Ekle</a>
<a href="/Departman/PasifDepartmanListesi" class="btn btn-info" style="background-color:olive; color:aliceblue;">Pasif Departman Listesi</a>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>@ViewBag.DepartmanAdi Departmanındaki İlgili Personel Satışı</h2>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel Adı : @ViewBag.DepartmanPersoneliSatisi</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Ürün</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Cari</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Fiyat</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Adet</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Toplam</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Tarih</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">İşlemler</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.Urun.UrunAdi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.Cari.CariAdi @item.Cari.CariSoyadi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketFiyati ₺</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketAdedi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketToplamTutari ₺</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketTarihi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center"><a href="/Satis/SatisiYazdir/@item.SatisHareketID" class="btn btn-default" style="background-color:mediumslateblue; color:aliceblue">Kaydet</a></td>
        </tr>
    }
</table>
<a href="/Departman/DepartmanListesi" class="btn btn-outline-info">Departman Listesi</a>
<a href="/Personel/PersonelListesi" class="btn btn-outline-danger">Personel Listesi</a>
<a href="/Personel/PersonelKarti" class="btn btn-outline-success">Personel Detayları</a>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmaniYazdir.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar

@model List<Departman>

@{ Layout = null; }

<br />

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Adı</th>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Kapasitesi</th>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Durumu</th>

            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.DepartmanID</td>

                    <td>@x.DepartmanAdi</td>

                    <td>@x.DepartmanKapasitesi</td>

                    <td>@x.DepartmanDurumu</td>

                </tr>
            }



        </tbody>

    </table>
    <a href="/Departman/DepartmanListesi" class="btn btn-primary" style="color:aliceblue;">Departman Listesi</a>


    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function () {

            var table = $('#example').DataTable({

                lengthChange: false,

                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']


                //"language": {
                //        "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
                //    }

            });



            table.buttons().container()

                .appendTo('#example_wrapper .col-md-6:eq(0)');

        });</script>

</body>

</html>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/DepartmanlariYazdir.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar

@model List<Departman>

@{ Layout = null; }

<br />

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">ID</th>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Adı</th>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Kapasitesi</th>

                <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Durumu</th>

            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.DepartmanID</td>

                    <td>@x.DepartmanAdi</td>

                    <td>@x.DepartmanKapasitesi</td>

                    <td>@x.DepartmanDurumu</td>

                </tr>
            }



        </tbody>

    </table>
    <a href="/Departman/DepartmanListesi" class="btn btn-warning" style="color:aliceblue;">Departman Listesi</a>
    <a href="/Satis/SatislariYazdir" class="btn btn-primary" style="color:aliceblue;">Satış Listesi</a>
    <a href="/Cari/CarileriYazdir" class="btn btn-danger" style="color:aliceblue;">Cari Listesi</a>
    <a href="/Personel/PersonelleriYazdir" class="btn btn-success" style="color:aliceblue;">Personel Listesi</a>
    <a href="/Fatura/FaturalariYazdir" class="btn btn-secondary" style="color:aliceblue;">Fatura Listesi</a>
    <a href="/Urun/UrunleriYazdir" class="btn btn-info" style="color:aliceblue;">Ürün Listesi</a>


    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>
        $(document).ready(function () {

            var table = $('#example').DataTable({

                lengthChange: false,

                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']


                //"language": {
                //        "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
                //    }

            });



            table.buttons().container()

                .appendTo('#example_wrapper .col-md-6:eq(0)');

        });</script>

</body>

</html>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Departman/PasifDepartmanListesi.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@*@model List<Departman>*@


@using PagedList
@using PagedList.Mvc
@model PagedList<Departman>


@{ ViewBag.Title = "PasifDepartmanListesi";
    Layout = "~/Views/Shared/AdminLayout.cshtml"; }

<br />

@using (Html.BeginForm("PasifDepartmanListesi", "Departman", FormMethod.Get))
{
<p>
    Departman Adı : @Html.TextBox("aranacakKelime")
    <input type="submit" value="Ara" />
</p>}

<table class="table table-bordered" style="margin-top:20px;">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Adı</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Departman Kapasitesi</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">İşlemler</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
<tr>
    <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
    <td style="display:table table-cell; vertical-align:middle;">@item.DepartmanAdi</td>
    <td style="display:table table-cell; vertical-align:middle;">@item.DepartmanKapasitesi</td>
    <td style="display:table table-cell; vertical-align:middle;" class="text-center">
        <a href="/Departman/DepartmaniAktifEt/@item.DepartmanID" class="btn" style="background-color:mediumpurple; color:aliceblue">Aktif Et</a>
    </td>
</tr>}
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("PasifDepartmanListesi", new { sayfa }),
new PagedListRenderOptions@*Sayfa değerine her tıklandığında, yeni bir sayfa oluşturarak bana Kategori Listesini aç*@
{
                LiElementClasses = new List<string>
                        {
"page-link"         //Sayfanın linklerini ekle
                }
            })

<a href="/Departman/DepartmanListesi" class="btn btn-info" style="background-color:darkcyan; color: aliceblue;">Aktif Departman Listesi</a>