MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Models/Siniflar/Cari.cs
using MVC_Ticari_Otomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_Ticari_Otomasyon.Models.Siniflar
{
    public class Cari
    {
        [Key]
        public int CariID { get; set; }


        [Display(Name = "Cari Adı")]
        [Column(TypeName = "Varchar")]
        [Required(ErrorMessage = "Cari adını boş geçemezsiniz!")]
        [StringLength(25, ErrorMessage = "Cari adı için en fazla 25 karakter girilebilir!")]
        public string CariAdi { get; set; }



        [Display(Name = "Cari Soyadı")]
        [Column(TypeName = "Varchar")]
        [Required(ErrorMessage = "Cari soyadını boş geçemezsiniz!")]
        [StringLength(25, ErrorMessage = "Cari soyadı için en fazla 25 karakter girilebilir!")]
        public string CariSoyadi { get; set; }




        [Display(Name = "Cari Görseli")]
        [Column(TypeName = "Varchar")]
        [Required(ErrorMessage = "Cari görselini boş geçemezsiniz!")]
        [StringLength(250, ErrorMessage = "Cari görseli için en fazla 250 karakter girilebilir!")]
        public string CariGorseli { get; set; }




        [Display(Name = "Cari Şehri")]
        [Column(TypeName = "Varchar")]
        [StringLength(15, ErrorMessage = "Cari şehri en fazla 15 karakter girilebilir!")]
        public string CariSehir { get; set; }




        [Display(Name = "Cari Mesleği")]
        [Column(TypeName = "Varchar")]
        [StringLength(25, ErrorMessage = "Cari mesleği en fazla 25 karakter girilebilir!")]
        public string CariMeslek { get; set; }




        [Display(Name = "Cari Maili")]
        [Column(TypeName = "Varchar")]
        [Required(ErrorMessage = "Cari mailini boş geçemezsiniz!")]
        [StringLength(50, ErrorMessage = "Cari maili için en fazla 50 karakter girilebilir!")]
        public string CariMaili { get; set; }



        [Display(Name = "Cari Şifresi")]
        [Column(TypeName = "Varchar")]
        //[Required(ErrorMessage = "Cari şifresini boş geçemezsiniz!")]
        [StringLength(20, ErrorMessage = "Cari şifresi için en fazla 20 karakter girilebilir!")]
        public string CariSifresi { get; set; }



        private bool _ilkDurumDegeri = true;
        [Display(Name = "Cari Durumu")]
        [Column(TypeName = "bit")]
        public bool CariDurumu
        {
            get
            {
                return _ilkDurumDegeri;
            }
            set
            {
                _ilkDurumDegeri = value;
            }
        }





        //[RegularExpression(@"^(05(\d{9}))$", ErrorMessage = "Girilen Telefon Numarası İstenilen Formatta Değildir!")]
        [Display(Name = "Cari Telefonu")]
        [Column(TypeName = "Varchar")]
        [StringLength(11, ErrorMessage = "Cari telefonu için en fazla 11 karakter girilebilir!")]
        public string CariTelefonu { get; set; }





        [Display(Name = "Cari Adresi")]
        [Column(TypeName = "Varchar")]
        [StringLength(150, ErrorMessage = "Cari adresi için en fazla 150 karakter girilebilir!")]
        public string CariAdresi { get; set; }





        [Column(TypeName = "Char")]
        [StringLength(1)]
        [Required(ErrorMessage = "Cari yetkisi tanımlayınız!")]
        public string Yetki { get; set; }



        public ICollection<SatisHareket> SatisHarekets { get; set; }              //1 Carinin 1'den fazla(Çok) SatisHareketi olabilir
    }
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Controllers/CariController.cs
using MVC_Ticari_Otomasyon.Models.Siniflar;
using PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Ticari_Otomasyon.Controllers
{
    public class CariController : Controller
    {
        // GET: Alert
        Context context = new Context();


        // GET: Cari
        public ActionResult CariListesi(string aranacakKelime, int sayfa = 1)
        {
            var cariler = from x in context.Cariler where x.CariDurumu == true select x;
            if (!string.IsNullOrEmpty(aranacakKelime))
            {
                cariler = cariler.Where(y => y.CariAdi.Contains(aranacakKelime) || y.CariSoyadi.Contains(aranacakKelime));
            }


            return View(cariler.ToList().ToPagedList(sayfa, 10));



            //var degerler = context.Cariler.Where(x=>x.CariDurumu==true).ToList();
            //return View(degerler);
        }





        public ActionResult PasifCariListesi(string aranacakKelime, int sayfa = 1)
        {
            var cariler = from x in context.Cariler where x.CariDurumu == false select x;
            if (!string.IsNullOrEmpty(aranacakKelime))
            {
                cariler = cariler.Where(y => y.CariAdi.Contains(aranacakKelime) || y.CariSoyadi.Contains(aranacakKelime));
            }


            return View(cariler.ToList().ToPagedList(sayfa, 10));


            //var degerler = context.Cariler.Where(x => x.CariDurumu == false).ToList();
            //return View(degerler);
        }





        public ActionResult CariyiAktifEt(int id)
        {
            var deger = context.Cariler.Find(id);
            deger.CariDurumu = true;
            context.SaveChanges();
            return RedirectToAction("CariListesi");
        }






        [HttpGet]
        public ActionResult CariEkle()
        {
            List<SelectListItem> deger1 = (from x in context.PersonelYetkileri.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.YetkiAdi,
                                               Value = x.YetkiID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;


            return View();
        }

        [HttpPost]
        public ActionResult CariEkle(Cari cari)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaAdi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Images/" + dosyaAdi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                cari.CariGorseli = "/Images/" + dosyaAdi + uzanti;
            }

            cari.CariDurumu = true;           //Class'da Durum için yazılan kodlar yerine sadece bu satırı da yazabiliriz.
            context.Cariler.Add(cari);
            context.SaveChanges();
            return RedirectToAction("CariListesi");

        }










        public ActionResult CariSil(int id)
        {
            var deger = context.Cariler.Find(id);
            deger.CariDurumu = false;
            context.SaveChanges();
            return RedirectToAction("CariListesi");
        }








        public ActionResult CariGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in context.PersonelYetkileri.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.YetkiAdi,
                                               Value = x.YetkiID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;



            var deger = context.Cariler.Find(id);
            return View("CariGetir", deger);
        }


        public ActionResult CariGuncelle(Cari cari)
        {
            if (Request.Files.Count > 0)
            {
                string dosyaAdi = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/Images/" + dosyaAdi + uzanti;
                Request.Files[0].SaveAs(Server.MapPath(yol));
                cari.CariGorseli = "/Images/" + dosyaAdi + uzanti;
            }

            var deger = context.Cariler.Find(cari.CariID);
            deger.CariAdi = cari.CariAdi;
            deger.CariSoyadi = cari.CariSoyadi;
            deger.CariGorseli = cari.CariGorseli;
            deger.CariMaili = cari.CariMaili;
            deger.CariSehir = cari.CariSehir;
            deger.CariMeslek = cari.CariMeslek;
            deger.CariTelefonu = cari.CariTelefonu;
            deger.CariAdresi = cari.CariAdresi;
            deger.Yetki = cari.Yetki;
            context.SaveChanges();
            return RedirectToAction("CariListesi");

        }








        public ActionResult CariSatisGecmisi(int id)
        {
            var degerler = context.SatisHareketleri.Where(x => x.Cariid == id).ToList();
            var cr = context.Cariler.Where(x => x.CariID == id).Select(y => y.CariAdi + " " + y.CariSoyadi).FirstOrDefault();
            ViewBag.Cari = cr;
            return View(degerler);
        }












        //public ActionResult CariyiYazdir(int id)                //Sadece bu Carinin özelliklerini yazdırmak için bu kod gerekli
        //{
        //    var degerler = context.Cariler.Where(x => x.CariID == id).ToList(); ;
        //    return View(degerler);
        //}



        public ActionResult CarileriYazdir()
        {
            var degerler = context.Cariler.ToList();
            return View(degerler);
        }
    }
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Cari/CariEkle.cshtml
@model MVC_Ticari_Otomasyon.Models.Siniflar.Cari
@{
    ViewBag.Title = "CariEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Ekleme Sayfası</h2>
<br />

<form class="form-group" method="post" , new { enctype="multipart/form-data" }>

    Cari Görseli
    <input type="file" name="CariGorseli" />
    <br />

    Cari Adı
    @Html.TextBoxFor(x => x.CariAdi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAdi, "", new { @style = "color:red" }) @*Cari Class'ında Validation Kuralları ve Hata mesajlarını yazıp Controllerde                                                                             ModelState.ISvalid yapısını tanımlamadan bu mesaj kullanılamıyor.*@
    <br />
    Cari Soyadı
    @Html.TextBoxFor(x => x.CariSoyadi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSoyadi, "", new { @style = "color:red" })
    <br />

    Cari Şehri
    @Html.TextBoxFor(z => z.CariSehir, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />

    Cari Mesleği
    @Html.TextBoxFor(z => z.CariMeslek, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariMeslek, "", new { @style = "color:red" })
    <br />

    Cari Maili
    @Html.TextBoxFor(z => z.CariMaili, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariMaili, "", new { @style = "color:red" })
    <br />

    Cari Telefonu
    @Html.TextBoxFor(z => z.CariSehir, new { @class = "form-control", @type = "phone" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />
    
    Cari Adresi
    @Html.TextAreaFor(z => z.CariSehir, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />

    Cari Yetkisi
    @Html.DropDownListFor(x => x.CariSehir, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />

    <button class="btn btn-success">Kaydet</button>
    <a href="/Cari/CariListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Personel Listesi</a>
</form>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Cari/CariGetir.cshtml
@model MVC_Ticari_Otomasyon.Models.Siniflar.Cari
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="form-group">
    @Html.HiddenFor(x => x.CariID)

    Cari Görseli
    <input type="file" name="CariGorseli" />
    <br />
    Cari Adı
    @Html.TextBoxFor(z => z.CariAdi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAdi, "", new { @style = "color:red" })
    <br />
    Cari Soyadı
    @Html.TextBoxFor(z => z.CariSoyadi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSoyadi, "", new { @style = "color:red" })
    <br />
    Cari Şehri
    @Html.TextBoxFor(z => z.CariSehir, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />
    Cari Mesleği
    @Html.TextBoxFor(z => z.CariMeslek, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariMeslek, "", new { @style = "color:red" })
    <br />
    Cari Maili
    @Html.TextBoxFor(z => z.CariMaili, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariMaili, "", new { @style = "color:red" })
    <br />
    Cari Telefonu
    @Html.TextBoxFor(z => z.CariTelefonu, new { @class = "form-control" , @type = "phone" })
    @Html.ValidationMessageFor(x => x.CariTelefonu, "", new { @style = "color:red" })
    <br />Cari Adresi
    @Html.TextAreaFor(z => z.CariAdresi, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAdresi, "", new { @style = "color:red" })
    <br />
    Cari Yetkisi
    @Html.DropDownListFor(x => x.Yetki, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.Yetki, "", new { @style = "color:red" })
    <br />
</div>
    <br />
    <button class="btn" style="background-color:#a725a4; color:antiquewhite">Değişiklikleri Kaydet</button>
    <a href="/Cari/CariListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Cari Listesi</a>
}

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Cari/CariListesi.cshtml
@*@using MVC_Ticari_Otomasyon.Models.Siniflar
    @model List<Cari>*@

@using MVC_Ticari_Otomasyon.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList<Cari>

@{ ViewBag.Title = "CariListesi";
    Layout = "~/Views/Shared/AdminLayout.cshtml"; }

<br />

@using (Html.BeginForm("CariListesi", "Cari", FormMethod.Get))
{
<p>
    Cari Adı : @Html.TextBox("aranacakKelime")
    <input type="submit" value="Ara" />
</p>}

<table class="table table-bordered" style="margin-top:20px;">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Fotoğraf</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Cari</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Şehir</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Meslek</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Mail</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Telefon</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Adres</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Yetki</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">İşlemler</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
    <tr>
        <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
        <td style="display:table table-cell; vertical-align:middle;" class="text-center">
            @if (item.CariGorseli == null || item.CariGorseli == "")
            {
                <img src="~/Images/resim-yok.png" width="120" height="80" /> 
            }
            else
            {
                <img src="@item.CariGorseli" width="120" height="80" />
            }
        </td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariAdi @item.CariSoyadi</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariSehir</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariMeslek</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariMaili</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariTelefonu</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariAdresi</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.Yetki</td>
        <td style="display:table table-cell; vertical-align:middle;" class="text-center">
            <a href="/Cari/CariGetir/@item.CariID" class="btn" style="background-color:darkorange; color:aliceblue">Güncelle</a>
            <a href="/Cari/CariSil/@item.CariID" class="btn" style="background-color:firebrick; color:aliceblue">Sil</a>
            <a href="/Cari/CariSatisGecmisi/@item.CariID" class="btn" style="background-color:plum; color:aliceblue">Satış Geçmişi</a>
        </td>
    </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("CariListesi", new { sayfa }),
new PagedListRenderOptions@*Sayfa değerine her tıklandığında, yeni bir sayfa oluşturarak bana Kategori Listesini aç*@
{
                LiElementClasses = new List<string>
                                    {
"page-link"         //Sayfanın linklerini ekle
                }
            })

<a href="/Cari/CariEkle" class="btn btn-info">Cari Ekle</a>
<a href="/Cari/PasifCariListesi" class="btn btn-info" style="background-color:olive; color:aliceblue;">Pasif Cari Listesi</a>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Cari/CariSatisGecmisi.cshtml
@using MVC_Ticari_Otomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "CariSatisGecmisi";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Cari Satış Geçmişi</h2>
<br />

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari Adı : @ViewBag.Cari</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Ürün</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Personel</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Fiyat</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Adet</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Toplam</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Tarih</th>
        <th>İşlemler</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.Urun.UrunAdi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.Personel.PersonelAdi @item.Personel.PersonelSoyadi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketFiyati</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketAdedi</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketToplamTutari</td>
            <td style="display:table table-cell; vertical-align:middle;" class="text-center">@item.SatisHareketTarihi</td>
            <td><a href="/Satis/SatisiYazdir/@item.SatisHareketID" class="btn btn-default" style="background-color:mediumslateblue; color:aliceblue">Kaydet</a></td>
        </tr>
    }
</table>
<a href="/Cari/CariListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Cari Listesi</a>

MVC_Ticari_Otomasyon/MVC_Ticari_Otomasyon/Views/Cari/PasifCariListesi.cshtml
@*@using MVC_Ticari_Otomasyon.Models.Siniflar
    @model List<Cari>*@
@using MVC_Ticari_Otomasyon.Models.Siniflar
@using PagedList
@using PagedList.Mvc
@model PagedList<Cari>

@{ ViewBag.Title = "PasifCariListesi";
    Layout = "~/Views/Shared/AdminLayout.cshtml"; }

<br />

@using (Html.BeginForm("PasifCariListesi", "Cari", FormMethod.Get))
{
<p>
    Cari Adı : @Html.TextBox("aranacakKelime")
    <input type="submit" value="Ara" />
</p>}

<table class="table table-bordered" style="margin-top:20px;">
    <tr>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">#</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Fotoğraf</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Cari</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Şehir</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Meslek</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Mail</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Telefon</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Adres</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">Yetki</th>
        <th style="display:table table-cell; vertical-align:middle;" class="text-center">İşlemler</th>
    </tr>
    @{int sayac = 0;}
    @foreach (var item in Model)
    {
    <tr>
        <td style="display:table table-cell; vertical-align:middle;" class="text-center">@{sayac += 1;} @sayac</td>
        <td style="display:table table-cell; vertical-align:middle;" class="text-center">
            @if (item.CariGorseli == null || item.CariGorseli == "")
            {
                <img src="~/Images/resim-yok.png" width="120" height="80" /> 
            }
            else
            {
                <img src="@item.CariGorseli" width="120" height="80" />
            }
        </td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariAdi @item.CariSoyadi</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariSehir</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariMeslek</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariMaili</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariTelefonu</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.CariAdresi</td>
        <td style="display:table table-cell; vertical-align:middle;">@item.Yetki</td>
        <td style="display:table table-cell; vertical-align:middle;" class="text-center">
            <a href="/Cari/CariyiAktifEt/@item.CariID" class="btn" style="background-color:mediumpurple; color:aliceblue">Aktif Et</a>
        </td>
    </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("PasifCariListesi", new { sayfa }),
new PagedListRenderOptions@*Sayfa değerine her tıklandığında, yeni bir sayfa oluşturarak bana Kategori Listesini aç*@
{
                LiElementClasses = new List<string>
                        {
"page-link"         //Sayfanın linklerini ekle
                }
            })

<a href="/Cari/CariListesi" class="btn btn-info" style="background-color:darkcyan; color:aliceblue;">Aktif Cari Listesi</a>